version: '3'

services:
  db:
    build:
      context: ./custom-db
    environment:
      POSTGRES_DB: simple_ecommerce
      POSTGRES_USER: dennyrezky
      POSTGRES_PASSWORD: Password12346
    ports:
      - 5432:5432
    networks:
      - ecommerce
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  usersservice:
    build:
      context: ./usersservice
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - ecommerce
    
  productservice:
    build:
      context: ./productsservice
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - ecommerce

  transactionsservice:
    build:
      context: ./transactionservice
    ports:
      - 8082:8082
    depends_on:
      - db
    networks:
      - ecommerce

  zookeper:
    image: confluentinc/cp-zookeeper:7.1.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - ecommerce
    
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    environment:
      # KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ZOOKEEPER_CONNECT: zookeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_CUSTOMER_ID: c0
      KAFKA_CONFLUENT_LICENSE: "ABC123XYZ737BVT"
    networks:
      - ecommerce
    depends_on:
      - zookeper

networks:
 ecommerce:
  driver: bridge